project 'DocContact.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DocContact' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocContact
pod 'SideMenu'

  target 'DocContactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DocContactUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
